# This file defines our multi-container application
version: '3.8'

services:
  api:
    build: .
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
    depends_on:
      db:
        condition: service_healthy

  # Our PostgreSQL database service
  db:
    image: postgres:15-alpine # Use an official, lightweight PostgreSQL image
    volumes:
      - postgres_data:/var/lib/postgresql/data/ # Persists database data even if container is removed
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432" # Map host port 5432 to container port 5432 for local access
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: # Defines the named volume for data persistence