# nixpacks.toml

# Tell Nixpacks to use a Dockerfile to build the image
providers = ["docker"]

[phases.setup]
# This ensures that 'apt-get' is available
nixPkgs = ["...", "apt"]

[start]
# We don't need a start command here because it's defined in railway.toml
# The CMD from our Dockerfile will be used by default if startCommand is not set in railway.toml
cmd = "uvicorn app:app --host 0.0.0.0 --port $PORT"