# railway.toml (Final Version)

[build]
builder = "nixpacks" # Use the standard builder
# Tell the builder where the application root is within the repo
nixpacksConfigPath = "./05-user-post-api/nixpacks.toml" 

[deploy]
# This is the command Railway will run AFTER the database is ready
startCommand = "uvicorn app:app --host 0.0.0.0 --port {{.PORT}}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10