# railway.toml (Simple & Correct)

[build]
# This single line tells Railway: "To build this project,
# find and use the Dockerfile located at this path."
dockerfilePath = "./05-user-post-api/Dockerfile"